Traceback (most recent call last):
  File "/home/me/.local/bin/metta", line 8, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python3.10/site-packages/hyperon/metta.py", line 33, in main
    with open(args.file) as f: program = f.read()
  File "/usr/lib/python3.10/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 3349: invalid start byte
