thread '<unnamed>' panicked at lib/src/metta/types.rs:142:22:
Incorrect function type: (->)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at core/src/panicking.rs:223:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x7f3057466e5a - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::ha4a311b32f6b4ad8
   1:     0x7f30574b5d23 - core::fmt::write::h1866771663f62b81
   2:     0x7f305745b1d3 - <unknown>
   3:     0x7f3057466ca2 - <unknown>
   4:     0x7f30574692cd - <unknown>
   5:     0x7f3057469113 - std::panicking::default_hook::h82cc572fcb0d8cd7
   6:     0x7f3057469917 - std::panicking::rust_panic_with_hook::he21644cc2707f2c4
   7:     0x7f3057469776 - <unknown>
   8:     0x7f3057467339 - <unknown>
   9:     0x7f305746943c - rust_begin_unwind
  10:     0x7f305706138d - core::panicking::panic_nounwind_fmt::hde1cf3f55855f05a
  11:     0x7f3057061422 - core::panicking::panic_nounwind::hfc854da59c4c7125
  12:     0x7f30570615e6 - core::panicking::panic_cannot_unwind::h17e80b89bebc054f
  13:     0x7f30570a02e9 - metta_run
  14:     0x7f30570847ec - <unknown>
  15:     0x7f305706b959 - <unknown>
  16:     0x557807361282 - <unknown>
  17:     0x557807357b4b - _PyObject_MakeTpCall
  18:     0x5578073514c8 - _PyEval_EvalFrameDefault
  19:     0x557807361aec - _PyFunction_Vectorcall
  20:     0x55780734bae8 - _PyEval_EvalFrameDefault
  21:     0x557807361aec - _PyFunction_Vectorcall
  22:     0x55780734b9a2 - _PyEval_EvalFrameDefault
  23:     0x557807430e56 - <unknown>
  24:     0x557807430d26 - PyEval_EvalCode
  25:     0x557807457ae8 - <unknown>
  26:     0x5578074522ef - <unknown>
  27:     0x557807457885 - <unknown>
  28:     0x557807456e68 - _PyRun_SimpleFileObject
  29:     0x557807456b47 - _PyRun_AnyFileObject
  30:     0x55780744b02e - Py_RunMain
  31:     0x557807424d6d - Py_BytesMain
  32:     0x7f3057f46d90 - <unknown>
  33:     0x7f3057f46e40 - __libc_start_main
  34:     0x557807424c65 - _start
  35:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
timeout: the monitored command dumped core
Aborted
