Traceback (most recent call last):
  File "/home/me/.local/bin/metta", line 8, in <module>
    sys.exit(main())
  File "/home/me/.local/lib/python3.10/site-packages/hyperon/metta.py", line 35, in main
    for result in metta.run(program):
  File "/home/me/.local/lib/python3.10/site-packages/hyperon/runner.py", line 208, in run
    self._run_check_for_error()
  File "/home/me/.local/lib/python3.10/site-packages/hyperon/runner.py", line 222, in _run_check_for_error
    raise RuntimeError(err_str)
RuntimeError: Unexpected end of expression
real 0.18
user 0.12
sys 0.03
