name 'MeTTaLog' is not defined
[()]
[()]
[(Error (assertEqual (llm (Agent <motto.agents.metta_agent.DialogAgent object at 0x7f4598aa3ed0>) (user "Ping")) "Nice to meet you") 
Expected: ["Nice to meet you"]
Got: [(Error (llm (Agent <motto.agents.metta_agent.DialogAgent object at 0x7f4598aa3ed0>) (user "Ping")) Exception caught:
NameError: name 'MeTTaLog' is not defined

At:
  /opt/logicmoo_workspace/packs_sys/logicmoo_opencog/MeTTa/metta-wam/tests/python_compat/metta-motto/tests/motto/agents/metta_agent.py(53): __call__
  /opt/logicmoo_workspace/packs_sys/logicmoo_opencog/MeTTa/metta-wam/tests/python_compat/metta-motto/tests/motto/llm_gate.py(214): llm
  /opt/logicmoo_workspace/packs_sys/logicmoo_opencog/MeTTa/metta-wam/tests/python_compat/metta-motto/tests/motto/llm_gate.py(240): <lambda>
  /opt/logicmoo_workspace/packs_sys/logicmoo_opencog/MeTTa/metta-wam/tests/python_compat/hyperon-experimental_python/hyperon/atoms.py(346): execute
  /opt/logicmoo_workspace/packs_sys/logicmoo_opencog/MeTTa/metta-wam/tests/python_compat/hyperon-experimental_python/hyperon/atoms.py(176): _priv_call_execute_on_grounded_atom
  /opt/logicmoo_workspace/packs_sys/logicmoo_opencog/MeTTa/metta-wam/tests/python_compat/hyperon-experimental_python/hyperon/runner.py(31): run_step
  (17): run_step
)]
Missed result: "Nice to meet you")]
0.42user 0.10system 0:00.53elapsed 99%CPU (0avgtext+0avgdata 128692maxresident)k
0inputs+8outputs (0major+28913minor)pagefaults 0swaps
