[(Error (py-dict (("a") ("b" "c"))) Exception caught:
Exception: Syntax error in tuple_to_keyvalue

At:
  /home/me/.local/lib/python3.10/site-packages/hyperon/stdlib.py(236): tuple_to_keyvalue
  /home/me/.local/lib/python3.10/site-packages/hyperon/stdlib.py(241): <listcomp>
  /home/me/.local/lib/python3.10/site-packages/hyperon/stdlib.py(241): py_dict
  /home/me/.local/lib/python3.10/site-packages/hyperon/atoms.py(428): execute
  /home/me/.local/lib/python3.10/site-packages/hyperon/atoms.py(203): _priv_call_execute_on_grounded_atom
  /home/me/.local/lib/python3.10/site-packages/hyperon/runner.py(207): run
  /home/me/.local/lib/python3.10/site-packages/hyperon/metta.py(35): main
  /home/me/.local/bin/metta(8): <module>
)]
