[(Error (py-dict ("a" "b") ("b" "c")) Exception caught:
TypeError: py_dict() takes 1 positional argument but 2 were given

At:
  /home/yegoblynqueenne/.local/lib/python3.10/site-packages/hyperon/atoms.py(428): execute
  /home/yegoblynqueenne/.local/lib/python3.10/site-packages/hyperon/atoms.py(203): _priv_call_execute_on_grounded_atom
  /home/yegoblynqueenne/.local/lib/python3.10/site-packages/hyperon/runner.py(207): run
  /home/yegoblynqueenne/.local/lib/python3.10/site-packages/hyperon/metta.py(35): main
  /home/yegoblynqueenne/.local/bin/metta(8): <module>
)]
