[(Error (py-dict (("a") ("b" "c"))) Exception caught:
Exception: Syntax error in tuple_to_keyvalue

At:
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/stdlib.py(204): tuple_to_keyvalue
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/stdlib.py(209): <listcomp>
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/stdlib.py(209): py_dict
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/atoms.py(469): execute
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/atoms.py(234): _priv_call_execute_on_grounded_atom
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/runner.py(209): run
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/metta.py(35): main
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/venv/bin/metta(8): <module>
)]
