[(Error (py-dict ("a" "b") ("b" "c")) Exception caught:
TypeError: py_dict() takes 1 positional argument but 2 were given

At:
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/atoms.py(469): execute
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/atoms.py(234): _priv_call_execute_on_grounded_atom
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/runner.py(209): run
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/python/hyperon/metta.py(35): main
  /mnt/c/Users/me/Documents/Prolog/metta/metta-wam-win/venv/bin/metta(8): <module>
)]
